PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?term ?label ?definition
WHERE {
 {
   ?term rdfs:label ?label .
   ?term <http://purl.obolibrary.org/obo/IAO_0000115> ?definition .
 }
 FILTER(isIRI(?term) && regex(str(?term), "PLANP_"))
}



#PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
#SELECT DISTINCT ?term ?label
#WHERE {
#  { ?s1 ?p1 ?term .
#  }
#  UNION
#  { ?term ?p2 ?o2 . 
#  ?term rdfs:label ?label .
#  }
#  FILTER(isIRI(?term) && regex(str(?term), "PLANA_"))
#}

